export const SITE = {
  name: 'Glorious Health Ministries',
  shortName: 'Glorious Health',
  tagline: 'Healing Journey for Widows',
  description: 'A healing journey for widows built on gatherings, connection, and sisterhood.',
  verse: '3 John 1:2',
  nav: [
    { href: '/about/', label: 'About' },
    { href: '/gatherings/', label: 'Gatherings' },
    { href: '/connection/', label: 'Connection' },
    { href: '/sisterhood/', label: 'Sisterhood' },
    { href: '/contact/', label: 'Contact' },
  ],
  footerLinks: [
    { href: '/', label: 'Home' },
    { href: '/about/', label: 'About' },
    { href: '/gatherings/', label: 'Gatherings' },
    { href: '/connection/', label: 'Connection' },
    { href: '/sisterhood/', label: 'Sisterhood' },
    { href: '/contact/', label: 'Contact' },
  ],
  contactEmail: 'glorioushealth1@gmail.com',
  contactAddress: 'P.O. Box 9837, Henrico, VA 23228',
  yearStarted: 2026,
} as const;
